### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/var/folders/d0/b4_h__p170lcfd9sdb92ssnc...

### ISSUE THREAD

**Issue by kingostarr** [peele/plantuml-preview#11]
1. ... Enter sample plantuml code in atom
2. ... Toggle to PlantUML Preview

**Atom Version**: 1.4.0
**System**: Mac OS X 10.11.2
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.11.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/var/folders/d0/b4_h__p170lcfd9sdb92ssnc0000gn/T/plantuml-preview/sample.svg'

```
At fs.js:549

Error: ENOENT: no such file or directory, open '/var/folders/d0/b4_h__p170lcfd9sdb92ssnc0000gn/T/plantuml-preview/sample.svg'
    at Error (native)
    at Object.fs.openSync (fs.js:549:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:137:20)
    at Object.fs.readFileSync (fs.js:397:15)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:385:29)
    at /Users/davidking/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:310:23
    at exit (/Users/davidking/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:326:7)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:213:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:220:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:98:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  3x -0:43.6.0 plantuml-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "plantuml-preview": {
    "jarLocation": "/usr/local/bin/plantuml.jar"
  }
}
```
### Installed Packages

``` coffee
# User
language-plantuml, v0.2.0
plantuml-preview, v0.11.2

# Dev
No dev packages
```

**Comment by peele** [comment]
Was the filename specified with `@startuml`? If so can you provide that line. I see a similar but not the same error when that line provides a filename without extension.

**Comment by kingostarr** [comment]
Hey peele, I hadn't specified a file with @startuml.  I have now done that (and given it an extension) and can get an image generated.

**Comment by peele** [comment]
That should not be required and I should try to catch those errors... I'll dig around.
