### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, open '/var/folders/d7/2xy2y3lj3fg6csr3nw48_h3w...

### ISSUE THREAD

**Issue by hassan** [peele/plantuml-preview#15]
[Enter steps to reproduce below:]
1. Follow these directions to install and configure:
   http://trevershick.github.io/atom/2015/12/04/plantuml-snippets.html
2. Open a file e.g. example.pu
3. Select 'Toggle PlantUML Preview' from menu
4. Boom

**Atom Version**: 1.7.2
**System**: Mac OS X 10.9.5
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.11.2
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, open '/var/folders/d7/2xy2y3lj3fg6csr3nw48_h3w0000gn/T/plantuml-preview/diagram.svg'

```
At fs.js:584

Error: ENOENT: no such file or directory, open '/var/folders/d7/2xy2y3lj3fg6csr3nw48_h3w0000gn/T/plantuml-preview/diagram.svg'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.module.(anonymous function) [as openSync] (ATOM_SHELL_ASAR.js:159:20)
    at Object.fs.readFileSync (fs.js:431:33)
    at Object.fs.readFileSync (ATOM_SHELL_ASAR.js:427:29)
    at /Users/hassan/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:310:23
    at exit (/Users/hassan/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:326:7)
    at triggerExitCallback (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:215:47)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:229:18
    at Socket.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/buffered-process.js:100:18)
    at emitOne (events.js:82:20)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)
```
### Commands

```
  6x -0:47.5.0 core:close (atom-text-editor.editor.is-focused)
     -0:02.1.0 plantuml-preview:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "symbols-view",
      "linter-erb",
      "linter-rubocop",
      "atom-liquid-snippets"
    ],
    "themes": [
      "atom-dark-ui",
      "pastel-dark-theme"
    ]
  },
  "plantuml-preview": {
    "dotLocation": "/usr/local/bin/dot",
    "jarLocation": "/usr/local/share/plantuml.jar",
    "java": "/usr/bin/java"
  }
}
```
### Installed Packages

``` coffee
# User
atom-ctags, v4.5.2
cucumber, v0.5.0
language-elixir, v0.12.3
language-haml, v0.24.0
language-liquid, v0.4.0
language-mustache, v0.13.0
language-plantuml, v0.2.0
language-ruby, v0.68.5
linter, v1.11.4
linter-liquid, v0.1.0
pastel-dark-theme, v0.1.2
plantuml-preview, v0.11.2
raml, v0.2.0
react, v0.15.0
regex-railroad-diagram, v0.16.0

# Dev
No dev packages
```

**Comment by hassan** [comment]
FYI: the error message is totally misleading - this doesn't occur if the source file's first line is '@startuml' and last line is '@enduml', which I thought were optional.
