### ISSUE TITLE
Uncaught Error: Could not call remote function ``. Check that the function signature is correct. ...

### ISSUE THREAD

**Issue by brobusta** [peele/plantuml-preview#19]
[Enter steps to reproduce below:]
1. Right Click on preview image
2. Choose Copy Diagram

**Atom Version**: 1.8.0
**System**: Ubuntu 12.04.5
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.11.2
### Stack Trace

Uncaught Error: Could not call remote function `. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
Error: Could not call remote function`. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
    at callFunction (/usr/share/atom/resources/atom.asar/browser/lib/rpc-server.js:205:11)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/lib/rpc-server.js:295:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)

```
At /usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:113

Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from 
    at callFunction (/usr/share/atom/resources/atom.asar/browser/lib/rpc-server.js:205:11)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/lib/rpc-server.js:295:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/usr/share/atom/resources/atom.asar/browser/api/lib/web-contents.js:133:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:113:13)
    at Object.RemoteMemberFunction [as writeImage] (/usr/share/atom/resources/atom.asar/renderer/api/lib/remote.js:204:16)
    at space-pen-div.atom.commands.add.core:copy (/work2/congvu/local_home/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:101:25)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchContextMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1106:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:340:25)
    at emitThree (events.js:97:13)
    at EventEmitter.emit (events.js:175:7)
```
### Commands

```
     -5:02.6.0 core:save (atom-text-editor.editor.is-focused)
  2x -4:59.2.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -4:55.3.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -4:53.1.0 editor:consolidate-selections (atom-text-editor.editor.mini.is-focused)
     -4:53.1.0 core:cancel (atom-text-editor.editor.mini.is-focused)
     -3:03.5.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -3:01.6.0 core:save (atom-text-editor.editor.is-focused)
     -2:40.2.0 core:copy (atom-text-editor.editor.is-focused)
  2x -2:39.1.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:37.2.0 core:save (atom-text-editor.editor.is-focused)
  5x -1:33.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:32.5.0 core:save (atom-text-editor.editor.is-focused)
     -1:26.5.0 core:copy (atom-text-editor.editor.is-focused)
     -1:25.4.0 core:paste (atom-text-editor.editor.is-focused)
  2x -1:25 core:save (atom-text-editor.editor.is-focused)
     -0:05.1.0 core:copy (img.uml-image.open-file)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "plantuml-viewer"
    ]
  },
  "plantuml-preview": {
    "dotLocation": "/usr/bin/dot",
    "jarLocation": "/work2/congvu/local_home/lib/plantuml.jar"
  }
}
```
### Installed Packages

``` coffee
# User
language-plantuml, v0.2.0
plantuml-preview, v0.11.2

# Dev
No dev packages
```

**Comment by peele** [comment]
Looks like an issue with writing png to clipboard on ubuntu/linux.
