### ISSUE TITLE
Uncaught ReferenceError: ext is not defined

### ISSUE THREAD

**Issue by jpluimers** [peele/plantuml-preview#24]
[Enter steps to reproduce below:]
1. Enable preview of a plantuml file as svg
2. Select the filename on the preview
3. Press Cmd-C (Mac OS X) to copy the filename (as the right-click context menu does not have a copy option)
4. The below error occurs

**Atom Version**: 1.10.2
**Electron Version**: 0.37.8
**System**: Mac OS X 10.9.5
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.12.0
### Stack Trace

Uncaught ReferenceError: ext is not defined

```
At /Users/jeroenp/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:117

ReferenceError: ext is not defined
    at space-pen-div.atom.commands.add.core:copy (/Users/jeroenp/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:117:99)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
  2x -3:08.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -3:07.6.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
  2x -3:07.2.0 editor:newline (atom-text-editor.editor.is-focused)
  2x -3:06.8.0 core:paste (atom-text-editor.editor.is-focused)
     -3:00.3.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -2:55.6.0 core:copy (atom-text-editor.editor.is-focused)
  3x -2:53.8.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
     -2:52.8.0 core:paste (atom-text-editor.editor.is-focused)
     -2:50.7.0 core:save (atom-text-editor.editor.is-focused)
     -1:50.5.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:49.4.0 core:move-down (atom-text-editor.editor.is-focused)
     -1:48.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:48 core:save (atom-text-editor.editor.is-focused)
     -0:59.1.0 plantuml-preview:open-file (img.uml-image.open-file.zoomToFit)
     -0:50.2.0 broadcast:start (img.uml-image.open-file.zoomToFit)
  3x -0:25.7.0 core:copy (div.plantuml-preview.padded.pane-item)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "atom-light-syntax"
    ]
  },
  "plantuml-preview": {
    "jarLocation": "/usr/local/Cellar/plantuml/8037/plantuml.8037.jar"
  }
}
```
### Installed Packages

``` coffee
# User
atom-beautify, v0.29.10 (active)
atom-keyboard-macros, v0.9.2 (inactive)
broadcast, v0.3.14 (active)
counter, v0.3.3 (active)
export-html, v3.0.0 (inactive)
file-icons, v1.7.18 (active)
language-batch, v0.3.3 (active)
language-bbcode, v0.1.1 (active)
language-inno, v2.1.6 (inactive)
language-innosetup, v2.2.1 (inactive)
language-pascal, v0.18.1 (active)
language-plantuml, v0.2.0 (active)
language-restructuredtext, v1.0.0 (active)
language-routeros-script, v0.2.0 (active)
nav-panel, v0.0.11 (active)
plantuml-preview, v0.12.0 (active)
print-atom, v0.1.1 (inactive)
rst-preview-pandoc, v0.1.12 (active)
sort-lines, v0.14.0 (active)
tabs-to-spaces, v1.0.2 (active)
atom-dark-syntax, v0.27.0 (inactive)
atom-dark-ui, v0.52.0 (inactive)
atom-light-syntax, v0.28.0 (active)
atom-light-ui, v0.44.0 (active)
base16-tomorrow-dark-theme, v1.1.0 (inactive)
base16-tomorrow-light-theme, v1.1.1 (inactive)
one-dark-ui, v1.5.0 (inactive)
one-light-ui, v1.5.0 (inactive)
one-dark-syntax, v1.3.0 (inactive)
one-light-syntax, v1.3.0 (inactive)
solarized-dark-syntax, v1.0.2 (inactive)
solarized-light-syntax, v1.0.2 (inactive)
about, v1.5.3 (active)
archive-view, v0.61.1 (active)
autocomplete-atom-api, v0.10.0 (active)
autocomplete-css, v0.11.2 (active)
autocomplete-html, v0.7.2 (active)
autocomplete-plus, v2.31.1 (active)
autocomplete-snippets, v1.11.0 (active)
autoflow, v0.27.0 (inactive)
autosave, v0.23.1 (active)
background-tips, v0.26.1 (active)
bookmarks, v0.41.0 (active)
bracket-matcher, v0.82.1 (active)
command-palette, v0.38.0 (inactive)
deprecation-cop, v0.54.1 (active)
dev-live-reload, v0.47.0 (active)
encoding-selector, v0.22.0 (active)
exception-reporting, v0.39.0 (active)
find-and-replace, v0.201.0 (active)
fuzzy-finder, v1.3.0 (active)
git-diff, v1.1.0 (active)
go-to-line, v0.31.0 (inactive)
grammar-selector, v0.48.1 (active)
image-view, v0.58.2 (active)
incompatible-packages, v0.26.1 (active)
keybinding-resolver, v0.35.0 (active)
line-ending-selector, v0.5.0 (active)
link, v0.31.1 (inactive)
markdown-preview, v0.158.0 (active)
metrics, v0.53.1 (active)
notifications, v0.65.0 (active)
open-on-github, v1.2.0 (inactive)
package-generator, v1.0.0 (inactive)
settings-view, v0.242.2 (active)
snippets, v1.0.2 (active)
spell-check, v0.67.1 (active)
status-bar, v1.4.1 (active)
styleguide, v0.47.0 (active)
symbols-view, v0.113.0 (inactive)
tabs, v0.100.2 (active)
timecop, v0.33.2 (active)
tree-view, v0.208.2 (active)
update-package-dependencies, v0.10.0 (active)
welcome, v0.34.0 (active)
whitespace, v0.33.0 (active)
wrap-guide, v0.38.1 (active)
language-c, v0.52.1 (active)
language-clojure, v0.21.0 (active)
language-coffee-script, v0.47.2 (active)
language-csharp, v0.12.1 (active)
language-css, v0.37.1 (active)
language-gfm, v0.88.0 (active)
language-git, v0.15.0 (active)
language-go, v0.42.1 (active)
language-html, v0.45.1 (active)
language-hyperlink, v0.16.0 (active)
language-java, v0.23.0 (active)
language-javascript, v0.119.0 (active)
language-json, v0.18.2 (active)
language-less, v0.29.5 (active)
language-make, v0.22.2 (active)
language-mustache, v0.13.0 (active)
language-objective-c, v0.15.1 (active)
language-perl, v0.35.0 (active)
language-php, v0.37.2 (active)
language-property-list, v0.8.0 (active)
language-python, v0.45.0 (active)
language-ruby, v0.69.0 (active)
language-ruby-on-rails, v0.25.0 (active)
language-sass, v0.56.0 (active)
language-shellscript, v0.22.4 (active)
language-source, v0.9.0 (active)
language-sql, v0.23.0 (active)
language-text, v0.7.1 (active)
language-todo, v0.28.0 (active)
language-toml, v0.18.0 (active)
language-xml, v0.34.9 (active)
language-yaml, v0.26.0 (active)

# Dev
No dev packages
```

**Comment by jpluimers** [comment]
Thanks. Does the fix copy the filename or the image itself?

**Comment by peele** [comment]
It gives you the option to copy the filename from either the image or the filename above the image. Separate options for copying the filename or the image. Context menu only, no keyboard shortcut.

**Comment by jpluimers** [comment]
Though I'm a keyboard person (long story some of it at https://wiert.me/category/power-user/keyboards-and-keyboard-shortcuts/ ) this surely work for now. Thanks!

**Comment by peele** [comment]
I'd like to have working keyboard shortcuts. The problem is identifying
what to copy. I should probably look into the tab indexing or something.
Closest to mouse pointer might defeat the point of keyboard shortcut.

**Comment by jpluimers** [comment]
Something like this? 

If the filename has the focus or is selected then copy that, otherwise copy the picture. 

In the mean time I've found a workaround : install the broadcast plugin, broadcast the preview to your browser (it opens localhost:8000) then copy from the browser.

**Comment by peele** [comment]
The filename or the image can be copied directly from Atom using the right click menu based on which one your mouse if over.

**Comment by jpluimers** [comment]
I meant for the Cmd-C / Ctrl-C copy shortcut on Mac / Windows.
