### ISSUE TITLE
Uncaught Error: Cannot find module 'atom-space-pen-views'

### ISSUE THREAD

**Issue by YoranSys** [peele/plantuml-preview#30]
Hi, 
since i update atom i can't use anymore plantuml-preview.
It seem that atom-space-pen-views was removed from the core of atom.

https://github.com/atom/atom-space-pen-views

**Atom**: 1.14.3 x64
**Electron**: 1.3.13
**OS**: elementary OS
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package 0.12.4

### Stack Trace

Uncaught Error: Cannot find module 'atom-space-pen-views'

```
At module.js:457

Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/usr/share/atom/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/plantuml-preview/lib/plantuml-preview-view.coffee:1:19)
    at /packages/plantuml-preview/lib/plantuml-preview-view.coffee:1:1)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at isPlantumlPreviewView (/packages/plantuml-preview/lib/plantuml-preview.coffee:9:26)
    at toggle (/packages/plantuml-preview/lib/plantuml-preview.coffee:36:6)
    at /packages/plantuml-preview/lib/plantuml-preview.coffee:100:71)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:3:59)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/app.asar/src/atom-environment.js:1164:28)
    at EventEmitter.outerCallback (/app.asar/src/application-delegate.js:320:25)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
```

### Commands

```
     -1:25.3.0 pane:reopen-closed-item (atom-pane.pane.active)
     -1:10.6.0 plantuml-preview:toggle (ul.list-inline.tab-bar.inset-panel)
     -0:47 application:new-file (ul.list-inline.tab-bar.inset-panel)
     -0:34.6.0 welcome:show (input.hidden-input)
     -0:28.5.0 core:paste (input.hidden-input)
     -0:25.2.0 core:confirm (input.hidden-input)
```

### Non-Core Packages

```
angularjs 0.4.0 
angularjs-helper 0.10.2 
plantuml-preview 0.12.4 
```

**Comment by peele** [comment]
atom-space-pen-views is not expected to be part of atom core, the dependency is specified in the package.json dependencies section.
```
  "dependencies": {
    "atom-space-pen-views": "^2.0.3",
    "fs-plus": "^2.0.0",
    "js-beautify": "^1.5.10"
  }
```
The package should be downloaded into the node_modules local to the package installation directory. The output below is using Linux Mint 18.1 MATE with atom 1.14.3 x64 and plantuml-preview 0.12.5. 
```
mint@mint-virtual-machine ~ $ ls ~/.atom/packages/plantuml-preview/node_modules/
abbrev                d             es6-weak-map       jquery       nopt                space-pen
async                 editorconfig  fs-plus            js-beautify  property-accessors  underscore
atom-space-pen-views  emissary      fuzzaldrin         lru-cache    proto-list          underscore-plus
bluebird              es5-ext       graceful-readlink  minimist     pseudomap
commander             es6-iterator  grim               mixto        rimraf
config-chain          es6-symbol    ini                mkdirp       sigmund
```
Can you run `ls ~/.atom/packages/plantuml-preview/node_modules/` and provide the results?

**Comment by YoranSys** [comment]
Thank you for quick response,
 It seem i don't have this folder.
After uninstall and reinstall plantuml-preview create the folder and now it's work !

Thank you for your great plugin and work.
