### ISSUE TITLE
Uncaught TypeError: Cannot read property 'activateItem' of undefined

### ISSUE THREAD

**Issue by ghost** [peele/plantuml-preview#6]
[Enter steps to reproduce below:]
1. Plugin running
2. Closed output window

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [plantuml-preview](https://github.com/peele/plantuml-preview) package, v0.9.0
### Stack Trace

Uncaught TypeError: Cannot read property 'activateItem' of undefined

```
At /Users/foxd/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:70

TypeError: Cannot read property 'activateItem' of undefined
    at /Users/foxd/.atom/packages/plantuml-preview/lib/plantuml-preview-view.coffee:70:19
    at Emitter.module.exports.Emitter.emit (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at /Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane-container.js:333:27
    at Pane.module.exports.Pane.observeActiveItem (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane.js:196:7)
    at /Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane-container.js:331:42
    at Emitter.module.exports.Emitter.emit (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at PaneContainer.module.exports.PaneContainer.setActivePane (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane-container.js:196:22)
    at Pane.module.exports.Pane.activate (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane.js:619:15)
    at PaneContainer.module.exports.PaneContainer.activateNextPane (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane-container.js:250:26)
    at Pane.module.exports.Pane.destroyed (/Applications/Productivity/Atom.app/Contents/Resources/app.asar/src/pane.js:642:24)
```
### Commands

```
     -2:36.1.0 core:copy (atom-text-editor.editor.is-focused)
     -2:33.8.0 core:paste (atom-text-editor.editor.is-focused)
  3x -2:17.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:00.1.0 core:move-down (atom-text-editor.editor.is-focused)
 11x -1:58.1.0 core:move-left (atom-text-editor.editor.is-focused)
     -1:55.4.0 core:move-right (atom-text-editor.editor.is-focused)
  4x -1:55 core:move-left (atom-text-editor.editor.is-focused)
 14x -1:54.2.0 core:move-right (atom-text-editor.editor.is-focused)
  2x -1:47.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:31.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:27.9.0 plantuml-preview:toggle (atom-text-editor.editor.is-focused)
  4x -0:32.7.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:28.8.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:24.5.0 core:backspace (atom-text-editor.editor.is-focused)
 26x -0:17.6.0 core:delete (atom-text-editor.editor.is-focused)
     -0:11.9.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-light-ui",
      "one-dark-syntax"
    ]
  },
  "plantuml-preview": {
    "jarLocation": "/users/foxd/plantuml.jar",
    "outputFormat": "png",
    "useTempDir": false,
    "bringFront": true
  }
}
```
### Installed Packages

``` coffee
# User
language-plantuml, v0.1.1
plantuml-preview, v0.9.0
plantuml-viewer, v0.7.0

# Dev
No dev packages
```

**Comment by peele** [comment]
Thank you.
